In [2]:
# %tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)
from tensorflow import keras
print(keras.__version__)

2.12.0
2.12.0


In [3]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [4]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 2533340732671859367
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 14328594432
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 5872193835754774827
 physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5"
 xla_global_id: 416903419]

In [5]:
268435456/1024/1024/1024

0.25

In [6]:
x=[[2,]] # 리스트
print(x)
# 리스트 입력
m=tf.matmul(x,x) # 행렬곱
print(type(m)) # EagerTensor 2.0부터는 eager mode/ 이전 graph mode
# pytorch / py torch 동시에 사용
# pytorch : tensorflow의 2.x형식하고 동일 (프로그램하기가 편리) # openAPI가 pytorch를 사용
# YOLOv4까지는 tensorflow로 망을 구성 YOLOv5부터는 pytorch를 사
# tensorflow 2x버전부터 pytorch 같은 형식으로 변경(keras 이용)
print('hello, {}'.format(m))

[[2]]
<class 'tensorflow.python.framework.ops.EagerTensor'>
hello, [[4]]


In [7]:
# tensorflow에서도 broadcasting이 통한다
# 
a=tf.constant([[1,2],[3,4]])
print(a)
b=a+tf.constant([1])
print(b)
print(type(b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
print(a*b)
print(a+b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 5]
 [7 9]], shape=(2, 2), dtype=int32)


In [10]:
import numpy as np
c=np.multiply(a,b)
print(c)
print(type(c)) # <class 'numpy.ndarray'>

[[ 2  6]
 [12 20]]
<class 'numpy.ndarray'>


In [11]:
# tf1.x 버전에서 작동하는 방식 (constant,variables,placeholder)
# static mode : graph mode
with tf.compat.v1.Session() as sess: # session : 네트워크에서 사용하는 단어(GPU네트워크로 연결)
  x=tf.compat.v1.placeholder(tf.float32) # 데이터를 받는 구역
  y=tf.square(x)
  z=tf.add(x,y) # run은 가장 마지막 node를 호출하면 연결된 모든 node를 계산해서 결괄르 출력
  z0=sess.run([z],feed_dict={x:2.}) # 데이터를 피딩
  z1=sess.run([z],feed_dict={x:2.,y:2.})
print('z0:{}.\nz1:{}'.format(z0,z1))

z0:[6.0].
z1:[4.0]


In [12]:
# tensorflow 2.0에서 function base로 전환 : dynamic mode/eager mode
# function base programming으로 전
import tensorflow as tf
def add(x,y):
  return x+y
@tf.function 
def compute_z1(x,y):
  return add(x,y)
@tf.function
def compute_z0(x):
  return tf.add(x,tf.square(x))
z0=compute_z0(2.)
z1=compute_z1(2.,2.)
print('z0:{}.\nz1:{}'.format(z0,z1))

z0:6.0.
z1:4.0
