In [1]:
import numpy as np
print(np.__version__)
print(np.eye(5)) # 단위행렬
np.identity(5) # 항등원 : +,0 : *,1 : 행렬,단위행렬

1.22.4
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# n차원 행렬 == 다차원 행렬
# 행우선 : C-style, 열우선 == Fortran 열우선
first = np.ndarray(shape=(2,2), dtype=float, order='F') # 행열 어떤 것이던지 사용이 가능 
first.fill(10)
first

array([[10., 10.],
       [10., 10.]])

In [7]:
# for 문 뒤에 range ( 시작값값, 종료값, 증감값 )
# for ( 초기값, 한계값, 증감값 )
print(np.arange(10))
array = np.arange(10).reshape(5, 2)
print("원배열 : \n", array)

b = np.ones_like(array, float)
print("\n동일 사이즈행렬 : \n", b)

array = np.arange(8)
c = np.ones_like(array)
print("\nMatrix c : \n", c)

[0 1 2 3 4 5 6 7 8 9]
원배열 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

동일 사이즈행렬 : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Matrix c : 
 [1 1 1 1 1 1 1 1]


In [6]:
c= np.arange(10)
print(c)
print(type(c))
c_copy=c[0:5] # slice 부분집합 ( 뒤는 포함이 안됨)
print(c_copy)

c_copy[0:2]=100
print(c)
print(c_copy) # 원본이 수정 ( 주소에 의한 참조)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 1 2 3 4]
[100 100   2   3   4   5   6   7   8   9]
[100 100   2   3   4]


In [19]:
e = np.arange(24).reshape(2,3,4) # 면, 행, 열
print(e)
print(e.flatten()) # 1차원으로 => 
e= np.arange(24).reshape(1,2,3,4)
print("차원확대")
print(e)
print("차원축소")

e=e.reshape(-1,4) # 나머지 다다
print(e)
print(e[1])


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
차원확대
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]
차원축소
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[4 5 6 7]
24


In [12]:
def pprint(arr):
  print("type:{}".format(type(arr)))
  print(f"shape: {arr.shape}, dimension: {arr.ndim}, dtype:{arr.dtype}")
  print("배열 데이터:\n", arr)
arr = [1,2,3]
a= np.array([1,2,3]) # list로 데이터 생성
pprint(a)

type:<class 'numpy.ndarray'>
shape: (3,), dimension: 1, dtype:int64
배열 데이터:
 [1 2 3]


In [20]:
a=np.arange(10)
print(type(a))
print(a.dtype)
print(a.shape)
print(a.ndim)
print("바이트오더", a.dtype.byteorder) # 변화 big endian, little endian
print("아이템사이즈", a.dtype.itemsize) # 데이터의 바이트 수
print("타입의 이름",a.dtype.type) 
print(a.size)
print(a.astype(np.float32)) # 타입 변경
print(a.dtype.itemsize*a.size) # 메모리 용량

<class 'numpy.ndarray'>
int64
(10,)
1
바이트오더 =
아이템사이즈 8
타입의 이름 <class 'numpy.int64'>
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
80


In [24]:
# 문제
# 다음 2차원 리스트를 ndarray로 변환해 보시오
# [[1,2],[3,4]]

test=np.arange(4)+1
testarr = np.ndarray(shape=(2,2), dtype=float, order='F')

np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [27]:
# 문제 
# 이 데이터를 arrange를 이용해서 작성하기
a=np.array([[11,12,13,14,15],
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30],
            [31,32,33,34,35]])

np.arange(11,36).reshape(5,5)

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [28]:
a.transpose() # 변환 데이터를 리턴( 원본을 변경하지 않음 )

array([[11, 16, 21, 26, 31],
       [12, 17, 22, 27, 32],
       [13, 18, 23, 28, 33],
       [14, 19, 24, 29, 34],
       [15, 20, 25, 30, 35]])

In [29]:
a

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [35]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3x3 행렬
print(arr2d)
print(arr2d[:2])
print("구분선1")
print(arr2d[0])
print(arr2d[0][2])
print(arr2d[0,2])

print("구분선")

print(arr2d[:2])
print(arr2d[:2,1:])
print(arr2d[1,:2])
print(arr2d[2,:1])
arr2d[:2,:1]=0

print(arr2d.ndim)
print(arr2d.strides) # 24,8 # 다음 행이 나올려면 24바이트를 지나가야되고, 다음 열이 나올려면 8바이트를 지나가야함
# 데이터는 메모리에 1차원으로 저장장

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
구분선1
[1 2 3]
3
3
구분선
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[4 5]
[7]
2
(24, 8)


In [37]:
# 요소연산과 내적
a=np.array([[1,2],
            [3,4]])
b=np.array([[4,3],
            [2,1]])

print(a+b)
print(a*b)
print(a.dot(b)) # 행렬곱은 내적의 연속이다. 앞 행렬의 행벡터를 뒤에있는 열벡터의 숫자만큼 특성추출

[[5 5]
 [5 5]]
[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]


In [49]:
arr3d=np.arange(1,13).reshape(2,2,3)
print("첫면은", arr3d[0])
print('첫면 첫행은 =', arr3d[0][0])
print("첫면 첫행, 첫요소는 =", arr3d[0][0][0])

# 문제
# 위 데이터의 차원,차수,데이터타입, strides를 알아보시오

arr3d
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.dtype)
print(arr3d.strides)

첫면은 [[1 2 3]
 [4 5 6]]
첫면 첫행은 = [1 2 3]
첫면 첫행, 첫요소는 = 1
3
(2, 2, 3)
int64
(48, 24, 8)


In [50]:
old_values=arr3d.copy() # 명시적으로 복사, 원본은 백업
arr3d[0]=42
print("값의 변경후")
print(arr3d)
print("이전 값으로 복구")
arr3d=old_values
print(arr3d)

값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
Z = np.arange(36)
print(Z)
Z=Z.reshape((6,6))
print(Z[1:5,1:5]) # 교차지점을 선택

print("구분선")
print(Z[[1,2,3],[1,2,3]]) # 순서대로 두개씩 짝을 지어서 인덱싱싱
A=Z[1:5,1:5] # 복사가 아니라 slicing view 복사하려면 명시적으로 .copy()를 달아줘야함
A[0,0]=9
print(A)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 7  8  9 10]
 [13 14 15 16]
 [19 20 21 22]
 [25 26 27 28]]
구분선
[ 7 14 21]
[[ 9  8  9 10]
 [13 14 15 16]
 [19 20 21 22]
 [25 26 27 28]]
[[ 0  1  2  3  4  5]
 [ 6  9  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [57]:
arr=np.arange(32).reshape((8,4))
print(arr)

print(arr[0,3]) # 3
print(arr[0:2,0:2]) # 교차지점 
print("조합인덱스")
print(arr[[1,5,7,2],[0,3,1,2]])

print("파이프")
print(arr[[1,5,7,2]][[0,3,1]])

# print(arr[[1,5,7,2]])

print("팬시")
print(arr[[1,2,5,7]][:,[0,1,2,3]])
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
3
[[0 1]
 [4 5]]
조합인덱스
[ 4 23 29 10]
파이프
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
팬시
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [83]:
test=np.arange(36).reshape((6,6))
for i in range(1,6):
  test[i]=test[i-1]+10
print(test)

arr=[]
for i in range(6):
  ad=[]
  for j in range(6):
    ad.append(i*10+j)
  arr.append(ad)

a=np.arange(0,6)
arr=np.array([a,a+10,a+20,a+30,a+40,a+50])


# 문제 
# 하늘색 
# 팬시로 찾기
print("하늘색",test[3:6][:,[0,1,2,5]])

# 빨간색
# broadcasting
print("빨간색",test[[0,2,5],2])
# masking(boolean indexing)
mask=np.array([1,0,1,0,0,1],dtype=bool)
print(arr[mask,2])
print(arr[[1,0,1,0,0,1],2])
# 주황색
print("주황색", test[[0,1,2,3,4],[1,2,3,4,5]])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
하늘색 [[30 31 32 35]
 [40 41 42 45]
 [50 51 52 55]]
빨간색 [ 2 22 52]
[ 2 22 52]
[12  2 12  2  2 12]
주황색 [ 1 12 23 34 45]


In [110]:
test=np.arange(36).reshape((6,6))
for i in range(1,6):
  test[i]=test[i-1]+10

# 주황색
print("주황색\n",test[[0],[3,4]])

# 빨간색
print("빨간색\n",test[:,2])

# 연두색
print("연두색\n",test[[2,4]][:,[0,2,4]])

# 하늘색
print("하늘색\n",test[4:6,4:6])

주황색
 [3 4]
빨간색
 [ 2 12 22 32 42 52]
연두색
 [[20 22 24]
 [40 42 44]]
하늘색
 [[44 45]
 [54 55]]
